name: vt
description: Vector Tiles for Dart. Provides .pbf and/or .mvt parsers and needed classes.
version: 1.1.0
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_vt

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fixnum: ^1.0.1
  protobuf: ^2.1.0

dev_dependencies:
  test: ^1.21.3
  lints: ^2.0.0
